/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        //TestCases tests = new TestCases(); // Initialize your test class
            //Amazon amazon = new Amazon();
        //TODO: call your test case functions one after other here

        //tests.testCase01();
        // amazon.testCase1();

        //END Tests
            //amazon.endTest();

        //tests.endTest(); // End your test by clearning connections and closing browser
            //BookMyShowLinksCnt bookMyShowLinksCnt = new BookMyShowLinks();
            //bookMyShowLinksCnt.testCase2();
            //bookMyShowLinksCnt.endTest();

            // LinkedlnPost linkedlnPost = new LinkedlnPost();
            //  linkedlnPost.testCase3();
            //  linkedlnPost.endTest();

            // Frames frames = new Frames();
            // frames.testCase5();
            // frames.endTest();

           //LinkedlnImage linkedlnImage = new LinkedlnImage();
            //linkedlnImage.testCase6();
            //linkedlnImage.endTest();

            BookMyShow bookMyShow = new BookMyShow();
            bookMyShow.testCase2();
            bookMyShow.endTest();


    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
